import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Thai} from 'next/font/google'
import {Providers} from "./providers";

const inter = Noto_Sans_Thai({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trin Pongsri - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
